### ISSUE TITLE
Would rather not need to restart Chrome.

### ISSUE THREAD

**Issue by rokejulianlockhart** [adrium/knightadjuster#1]
> If Chrome is already running, it needs to be restarted to apply the changes

Does an issue exist for this upstream?

**Comment by adrium** [comment]
I would prefer leaving it open as well...

I looked at the source. The restart mechanism should be the same as the one when changing flags:
https://source.chromium.org/chromium/chromium/src/+/refs/tags/115.0.5736.0:chrome/browser/ui/webui/flags/flags_ui_handler.cc;l=178

I did not find a way to trigger `chrome::AttemptRestart()` via command line or dbus call. Maybe you can find one?

At least, color scheme changes are detected since version 114 and websites that support [prefers-color-scheme](https://developer.mozilla.org/en-US/docs/Web/CSS/@media/prefers-color-scheme) get changed. The respective bug has been closed recently:
https://bugs.chromium.org/p/chromium/issues/detail?id=998903

Implementation at:
https://source.chromium.org/chromium/chromium/src/+/refs/tags/115.0.5736.0:chrome/browser/ui/views/dark_mode_manager_linux.cc

No upstream issue exists that I know of.

**Comment by rokejulianlockhart** [comment]
Probably best to close as not planned then, rather than completed, unless I've misinterpreted something, @adrium.

**Comment by adrium** [comment]
Change reason

**Comment by rokejulianlockhart** [comment]
@adrium, I would be glad to file an issue upstream if that would help, but I'm not certain I could answer questions they ask. Would you CC yourself if I file one for you in Chromium?

**Comment by adrium** [comment]
Since dark/light appearance preference is now detected using the freedesktop portal settings, maybe there should be a flag, if Auto Dark Mode should be enabled (instead of only setting CSS prefers-color-scheme to dark)

Probably the same as the devtools checkbox behaves - just on every webpage: https://developer.chrome.com/docs/devtools/rendering/apply-effects/

Feel free to create a respective feature request, but I will not be able to answer questions either...
